### ISSUE TITLE
Update DSharpPlus to stable branch (4.1.0)

### ISSUE THREAD

**Issue by ghost** [captainkidd5/DevExchangeBot#27]
The DSharpPlus version the bot is currently using is `4.1.0-nightly-00930`. Recently, stable version `4.1.0` has come out which provides the same features without using the nightly build sources. The problem here is that the nightly sources seem to have become unavailable making it impossible to compile and run the bot anymore.

My suggestion would be to switch from the nightly build to the stable `4.1.0` version of DSharpPlus. It comes with the same features without the hassle of having to add additional NuGet sources to pull in the right packages. The bot is stable as-is, so nightly build sources would not be needed at this point.

**Comment by ghost** [comment]
"Simply" changing the version to `4.1.0` does not seem to work. The project will build successfully, but is unable to run. It throws the following exception:
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'DSharpPlus, Version=4.1.0.930, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'DSharpPlus, Version=4.1.0.930, Culture=neutral, PublicKeyToken=null'
   at DevExchangeBot.Program.MainAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DevExchangeBot.Program.MainAsync()
   at DevExchangeBot.Program.Main() in /home/delightedcat/Repositories/DevExchangeBot/src/Program.cs:line 35
```
I've already looked at this one last night without being able to make much sense of it. I tried to remove my local cache files with another `dotnet restore` hoping this would resolve the issue, without any luck.

@JustAeris Would you be able to look into this one, as you originally added the nightly sources to the project?

**Comment by JustAeris** [comment]
You can try removing the `IDoEverything.DSharpPlus.SlashCommands` package and replacing it with the new one simply called `DSharpPlus.SclashCommands`, since the latter is the official integration

**Comment by ghost** [comment]
Thank you for your reply, it seems to be that the new slash commands module is only available under the latest nightly build of version `4.2.0` of DSharpPlus. An attempt to install the nightly package led me to discover the `--prerelease` parameter in the `dotnet add package` command that allows the correct packages to be installed.

Because of this, the bot is now able to run again. I'm not expecting breaking changes of a minor version bump (`4.1.0` to `4.2.0`) but I'll test the bot for a bit to ensure it's working as intended. I'll merge my update branch once I did so!

**EDIT:** To clarify, this still means we'll use nightly builds. but this seems to be the only way to keep the bot up-to-date and to pull in the new slash commands package. It might mean more breaking API changes (according to the [documentation](https://dsharpplus.github.io/articles/misc/nightly_builds.html)), though.
